export const GET_COUNTRIES = 'GET_COUNTRIES';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_CONTINENT = 'ORDER_BY_CONTINENT';
export const GET_COUNTRY_NAME = 'GET_COUNTRY_NAME';
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';
export const ORDER_BY_ACTIVITY = 'ORDER_BY_ACTIVITY';
export const ORDER_ACT = 'ORDER_ACT';
export const POST_CREATE = 'POST_CREATE';